name: "Quality check"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Setup node
      shell: bash
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install
      shell: bash
      run: yarn

    - name: Quality check
      shell: bash
      run: yarn qualityCheck
