on:
  push:
    branches:
      - main
jobs:
  release:
    # 基本部分
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x"]
    name: Node ${{ matrix.node }}

    steps:
      - name: Initialize
        uses: ./.github/actions/qualityCheck

      # カスタム
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
